version: "3"
services:
  react-app-server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "80:3000" #80 -while using aws | 3000 -react
    volumes:
      - /app/node_modules
      - .:/app
  tests: #testservice
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
